version: '3.8'

services:
  app:
    container_name: artlist-crawler-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - REDIS_URL=${REDIS_URL}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - CHROME_PATH=${CHROME_PATH}
      - PORT=${PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    init: true